### ISSUE TITLE
how much faster can we benefit from KroneckerProductLazyTensor(*NonLazyTensor(w)) ?

### ISSUE THREAD

**Issue by wabyking** [panaali/word2ket#1]
It seems that GPytorch needs a Pytorch version bigger than 1.7. But I do not want to upgrade the PyTorch and still run the code. Can I safely use a nonlazy way to run EmbeddingKetXS? is it super slow?

**Comment by panaali** [comment]
@wabyking The non-lazy implementation shouldn't be slower than the lazy version but you may soon run out of memory if you decide to have a very large embedding matrix that doesn't fit in your GPU's memory.

**Comment by wabyking** [comment]
many thanks
